name: sikadu_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  intl: ^0.17.0
  lottie: ^1.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
    - assets/image/
  uses-material-design: true
